nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.2.cjs

packageExtensions:
  # firebase warnings fix
  "@firebase/analytics-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"

  "@firebase/app-check-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"

  "@firebase/auth-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"

  "@firebase/database@0.x":
    peerDependencies:
      "@firebase/app-types": "0.x"

  "@firebase/database-compat@0.x":
    peerDependencies:
      "@firebase/app-types": "0.x"

  "@firebase/firestore-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"
  
  "@firebase/functions@0.x":
    peerDependencies:
      "@firebase/app-types": "0.x"

  "@firebase/functions-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"

  "@firebase/installations-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"

  "@firebase/messaging-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"

  "@firebase/performance-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"

  "@firebase/remote-config-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"

  "@firebase/storage-compat@0.x":
    peerDependencies:
      "@firebase/app": "0.x"
      "@firebase/app-types": "0.x"

